# Copyright 2020-2025 Luke Murphy and Chris Croome
#
# This file is part of the Webarchitects Uncomplicated Firewall (UFW) Ansible role.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Uncomplicated Firewall (UFW) Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_ANY_ERRORS_FATAL: "1"
  ANSIBLE_CALLBACK_RESULT_FORMAT: "yaml"
  ANSIBLE_DEFAULT_VERBOSITY: "1"
  ANSIBLE_DIFF_ALWAYS: "1"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "0"
  ANSIBLE_FORCE_COLOR: "1"
  ANSIBLE_INJECT_FACT_VARS: "0"
  ANSIBLE_NOCOWS: "1"
  ANSIBLE_REMOTE_TMP: "/tmp"
  ANSIBLE_ROLES_PATH: "${CI_PROJECT_DIR}/..:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles"
  ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP: "1"
  DEBIAN_FRONTEND: "noninteractive"
  MOLECULE_VERBOSITY: "0"
  PRE_COMMIT_COLOR: always
  PY_COLORS: "1"
before_script:
  - whoami
  - pwd
  - which ansible
  - ansible --version
  - which yamllint
  - yamllint --version
  - which molecule
  - molecule --version
  # - ansible-galaxy collection list --format=json | yq -o=yaml -P
stages:
  - lint
  - bookworm
  - forky
  # Ubuntu Noble doesn't have a SSH app by default so the Molecule CI fails
  # - noble
  - trixie
lint:
  image: registry.git.coop/webarch/containers/images/trixie:20251009
  stage: lint
  script:
    - pre-commit install
    - pre-commit run --all-files
bookworm:
  image: registry.git.coop/webarch/containers/images/bookworm:20251009
  stage: bookworm
  script:
    - molecule test --all
forky:
  image: registry.git.coop/webarch/containers/images/forky:20251009
  stage: forky
  script:
    - molecule test --all
# noble:
#   image: registry.git.coop/webarch/containers/images/noble:20251009
#   stage: noble
#   script:
#     - molecule test --all
trixie:
  image: registry.git.coop/webarch/containers/images/trixie:20251009
  stage: trixie
  script:
    - molecule test --all
...
