---
# image: registry.git.coop/webarch/containers/images/ci:0.3.0
image: registry.git.coop/webarch/containers/images/ansible:0.8.0
variables:
  PY_COLORS: "1"
  ANSIBLE_FORCE_COLOR: "1"
before_script:
  - chmod 700 $(pwd)
  - ansible --version
  - ansible-lint --version
  - yamllint --version
stages:
  - lint
lint:
  stage: lint
  script:
    - molecule lint
...
