# Copyright 2020-2024 Luke Murphy and Chris Croome
#
# This file is part of the Webarchitects Uncomplicated Firewall (UFW) Ansible role.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Uncomplicated Firewall (UFW) Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
variables:
  ANSIBLE_CALLBACK_RESULT_FORMAT: "yaml"
  ANSIBLE_DISPLAY_SKIPPED_HOSTS: "0"
  ANSIBLE_FORCE_COLOR: "1"
  ANSIBLE_REMOTE_TMP: "/tmp"
  ANSIBLE_SHELL_ALLOW_WORLD_READABLE_TEMP: "1"
  MOLECULE_VERBOSITY: "0"
  PY_COLORS: "1"
before_script:
  - whoami
  - pwd
  - which ansible
  - ansible --version
  - which yamllint
  - yamllint --version
  - which molecule
  - molecule --version
stages:
  - lint
  - bookworm
  # - bullseye
  - jammy
  - noble
  - trixie
lint:
  image: registry.git.coop/webarch/containers/images/trixie:20240326
  stage: lint
  script:
    - pre-commit install
    - pre-commit run --all-files
bookworm:
  image: registry.git.coop/webarch/containers/images/bookworm:20240326
  stage: bookworm
  script:
    - molecule test
# bullseye:
#   image: registry.git.coop/webarch/containers/images/bullseye:20240326
#   stage: bullseye
#   script:
#     - molecule test
jammy:
  image: registry.git.coop/webarch/containers/images/jammy:20240326
  stage: jammy
  script:
    - molecule test
noble:
  image: registry.git.coop/webarch/containers/images/noble:20240326
  stage: noble
  script:
    - molecule test
trixie:
  image: registry.git.coop/webarch/containers/images/trixie:20240326
  stage: trixie
  script:
    - molecule test
...
