---
- name: Install and configure UFW
  block:

    - name: Install ufw
      apt:
        name: ufw
        state: present
        update_cache: true

    - name: Run allow rules
      ufw:
        rule: allow
        port: "{{ rule.port }}"
        proto: "{{ rule.proto }}"
        src: "{{ rule.src | default(omit) }}"
        state: enabled
      loop: "{{ ufw_allow_rules }}"
      loop_control:
        loop_var: rule
      notify: Restart ufw

    - name: Run disallow rules
      ufw:
        rule: deny
        port: "{{ rule.port }}"
        proto: "{{ rule.proto }}"
        state: enabled
      loop: "{{ ufw_disallow_rules }}"
      loop_control:
        loop_var: rule
      notify: Restart ufw

    - name: Default policy deny
      ufw:
        policy: deny
      when: ufw_default_policy_deny

    - name: Enable the firewall
      ufw:
        state: enabled
      tags:
        - molecule-notest

  tags:
    - ufw
...
