---
- name: Install and configure UFW
  block:

    - name: Install ufw
      ansible.builtin.apt:
        pkg:
          - ufw
        state: present
        update_cache: true

    - name: Get the UFW status
      ansible.builtin.command: ufw status
      check_mode: false
      changed_when: false
      register: ufw_check_status

    - name: Set a fact for the UFW status
      ansible.builtin.set_fact:
        ufw_status: "{{ ufw_check_status.stdout | community.general.jc('ufw') }}"

    - name: Debug UFW status
      ansible.builtin.debug:
        var: ufw_status
        verbosity: 2

    - name: Run allow rules
      community.general.ufw:
        rule: allow
        port: "{{ rule.port }}"
        proto: "{{ rule.proto }}"
        src: "{{ rule.src | default(omit) }}"
        state: enabled
      loop: "{{ ufw_allow_rules }}"
      loop_control:
        loop_var: rule
      notify: Restart ufw

    - name: Run disallow rules
      community.general.ufw:
        rule: deny
        port: "{{ rule.port }}"
        proto: "{{ rule.proto }}"
        state: enabled
      loop: "{{ ufw_disallow_rules }}"
      loop_control:
        loop_var: rule
      notify: Restart ufw

    - name: Default policy deny
      community.general.ufw:
        policy: deny
      when: ufw_default_policy_deny

    - name: Enable the firewall
      community.general.ufw:
        state: enabled

  when: ufw | bool
  tags:
    - ufw
...
