# Copyright 2020-2025 Luke Murphy and Chris Croome
#
# This file is part of the Webarchitects Uncomplicated Firewall (UFW) Ansible role.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Uncomplicated Firewall (UFW) Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
argument_specs:
  main:
    author: Chris Croome
    description: An Ansible to configure the Ubuntu UFW - Uncomplicated Firewall.
    short_description: The main entry point for the UFW role.
    options:
      ufw_app_allow_rules:
        type: list
        required: false
        description: Internal list of named allow rules.
      ufw_app_deny_rules:
        type: list
        required: false
        description: Internal list of named deny rules.
      ufw_applications_d:
        type: dict
        required: false
        description: Internal dictionary for the result of ansible.builtin.find.
      ufw_applicatons_path:
        type: dict
        required: false
        description: Internal dictionary for the result of ansible.builtin.stat.
      ufw_apps_available_d:
        type: dict
        required: false
        description: Internal variable for the result of cat'ing the contents of all the files in /etc/ufw/applications.d.
      ufw_apps_available_names:
        type: list
        required: false
        description: Internal list of UFW application names.
      ufw_apps_available:
        type: dict
        required: false
        description: Internal dictionary of all applications available.
      ufw_apps_available_list:
        type: list
        required: false
        description: Internal list of all applications available.
      ufw_apps_enabled:
        type: list
        elements: str
        required: false
        description: Internal list of enabled apps.
      ufw_apps_proposed:
        type: list
        elements: str
        required: false
        description: Internal list of proposed apps.
      ufw_apps_proposed_but_absent:
        type: list
        elements: str
        required: false
        description: Internal list of proposed apps that haven't yet been created.
      ufw_argument_spec:
        type: dict
        required: false
        description: Internal variable for the argument spec.
      ufw_check_status:
        type: dict
        required: false
        description: Internal variable for the results of ufw status.
      ufw_combined_argument_spec:
        type: dict
        required: false
        description: Internal variable for the combined argument spec.
      ufw_conf_file_b64encoded:
        type: dict
        required: false
        description: Internal variable for the results from slurping the contents of a configuration file.
      ufw_conf_file_contents:
        type: list
        required: false
        description: Internal variable for a list of the configuration file contents.
      ufw_conf_file_contents_dict:
        type: dict
        required: false
        description: Internal variable for a dictionry of the configuration file contents.
      ufw_conf_path:
        type: dict
        required: false
        description: Internal variable for a dictionry of the result of stat'ing the configuration file path.
      ufw_internal_argument_spec:
        type: dict
        required: false
        description: Internal variable for the internal argument spec.
      ufw_pkgs_present:
        type: dict
        required: false
        description: Internal variable for the results of installing packages.
      ufw_service:
        type: dict
        required: false
        description: Internal variables for the results from enabling the UFW service.
      ufw_status:
        type: dict
        required: false
        description: Internal dictionary generated from ufw status and the JC ufw parser.
      ufw_system_service:
        type: dict
        required: false
        description: Internal variable for the results of stat'ing /lib/systemd/system/ufw.service.
...
