# Copyright 2020-2023 Luke Murphy and Chris Croome
#
# This file is part of the Webarchitects Uncomplicated Firewall (UFW) Ansible role.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Uncomplicated Firewall (UFW) Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
# https://docs.ansible.com/ansible/latest/playbook_guide/complex_data_manipulation.html
ufwvarnames: "{{ q('varnames', '^ufw_') | sort }}"
ufwhostvars: "{{ dict(ufwvarnames | list | zip(q('vars', *ufwvarnames))) }}"

ufw_app_allow_rules: "{{ ufw_allow_rules | community.general.json_query('[].app') }}"
ufw_app_deny_rules: "{{ ufw_deny_rules | community.general.json_query('[].app') }}"

# This variable is populated when the role is run
# cat /etc/ufw/applications.d/* | jc --ini -yp
ufw_apps_available: {}

# ufw app list
# cat /etc/ufw/applications.d/* | jc --ini -p | jq 'keys' | yq -o=json -P
ufw_apps_available_names: "{{ ufw_apps_available.keys() }}"

ufw_apps_enabled: "{{ ufw_status | community.general.json_query('rules[*].to_service') }}"
ufw_apps_proposed: "{{ ufw_apps | community.general.json_query('[].app') }}"
ufw_apps_proposed_but_absent: "{{ ufw_app_allow_rules | ansible.builtin.difference(ufw_apps_available_names) }}"

# This variables is populated when the role is run
# ufw status | jc --ufw -yp
ufw_status: {}
...
