# Copyright 2020-2025 Luke Murphy and Chris Croome
#
# This file is part of the Webarchitects Uncomplicated Firewall (UFW) Ansible role.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects Uncomplicated Firewall (UFW) Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects Uncomplicated Firewall (UFW) Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
ansible_managed: "Ansible managed"

# https://docs.ansible.com/ansible/latest/playbook_guide/complex_data_manipulation.html
ufwvarnames: "{{ q('varnames', '^ufw_') | sort }}"
ufwhostvars: "{{ dict(ufwvarnames | list | zip(q('vars', *ufwvarnames))) }}"

# https://forum.ansible.com/t/validating-inventory-against-argument-specs/10748/10
ufw_validation_conditions:
  - >-
    {# Loop through the apps that are absent to check the path starts with /etc/ufw/applications.d #}
    {% if (ufw_apps_absent is defined) and (ufw_apps_absent != []) %}
    {%     for ufw_app in ufw_apps_absent %}
    {{         ufw_app.path | ansible.builtin.regex_search('^[/]etc[/]ufw[/]applications[.]d[/]') != None }}
    {%     endfor %}
    {% endif %}
  - >-
    {# Loop through the allow rules to check that they have either app or ports and proto specified #}
    {% if (ufw_allow_rules is defined) and (ufw_allow_rules != []) %}
    {%     for ufw_rule in ufw_allow_rules %}
    {{         (ufw_rule.app is defined) or ((ufw_rule.port is defined) and (ufw_rule.proto is defined)) }}
    {%     endfor %}
    {% endif %}
  - >-
    {# Loop through the deny rules to check that they have either app or ports and proto specified #}
    {% if (ufw_deny_rules is defined) and (ufw_deny_rules != []) %}
    {%     for ufw_rule in ufw_deny_rules %}
    {{         (ufw_rule.app is defined) or ((ufw_rule.port is defined) and (ufw_rule.proto is defined)) }}
    {%     endfor %}
    {% endif %}
ufw_validation: "{{ ufw_validation_conditions is ansible.builtin.all }}"

ufw_systemd_service_name: "{{ ufw_systemd_service_file | ansible.builtin.basename }}"

ufw_app_allow_rules: "{{ ufw_allow_rules | community.general.json_query('[].app') }}"
ufw_app_deny_rules: "{{ ufw_deny_rules | community.general.json_query('[].app') }}"

# These variables are populated when the role is run and files are found in /etc/ufw/applications.d
# cat /etc/ufw/applications.d/* | jc --ini -yp
ufw_apps_available: {}
ufw_apps_available_list: []

# This variables is populated when the role is run
# ufw status | jc --ufw -yp
ufw_status: {}

# ufw app list
# cat /etc/ufw/applications.d/* | jc --ini -p | jq 'keys' | yq -o=json -P
ufw_apps_available_names: "{{ ufw_apps_available.keys() }}"

ufw_apps_absent: "{{ ufw_apps | community.general.json_query('[?state==`absent`]') }}"
ufw_apps_enabled: "{{ ufw_status | community.general.json_query('rules[*].to_service') }}"
ufw_apps_present: "{{ ufw_apps | community.general.json_query('[?state==`present`]') }}"
ufw_apps_proposed: "{{ ufw_apps | community.general.json_query('[].app') }}"
ufw_apps_proposed_but_absent: "{{ ufw_apps_proposed | ansible.builtin.difference(ufw_apps_available_names) }}"
...
