---
dependency:
  name: galaxy
platforms:
  - name: instance
    image: registry.git.coop/webarch/containers/images/ansible:0.8.0
    pre_build_image: true
provisioner:
  name: ansible
lint: |
  set -e
  yamllint -f colored -c .yamllint .
  ansible-lint --force-color -c .ansible-lint . -vvv
